In [1]:
from sklearn.compose import ColumnTransformer, make_column_transformer
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder, PolynomialFeatures,SplineTransformer,FunctionTransformer
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge, Lasso
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold, GridSearchCV
from sklearn.neighbors import KNeighborsRegressor
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
import seaborn as sns
import numpy as np
import polars as pl

In [2]:
(body := 
 
 pl.read_csv('bodyfat.csv')


)

shape: (252, 15)
┌─────────┬─────────┬─────┬────────┬───┬───────┬────────┬─────────┬───────┐
│ density ┆ bodyfat ┆ age ┆ weight ┆ … ┆ ankle ┆ biceps ┆ forearm ┆ wrist │
│ ---     ┆ ---     ┆ --- ┆ ---    ┆   ┆ ---   ┆ ---    ┆ ---     ┆ ---   │
│ f64     ┆ f64     ┆ i64 ┆ f64    ┆   ┆ f64   ┆ f64    ┆ f64     ┆ f64   │
╞═════════╪═════════╪═════╪════════╪═══╪═══════╪════════╪═════════╪═══════╡
│ 1.0708  ┆ 12.3    ┆ 23  ┆ 154.25 ┆ … ┆ 21.9  ┆ 32.0   ┆ 27.4    ┆ 17.1  │
│ 1.0853  ┆ 6.1     ┆ 22  ┆ 173.25 ┆ … ┆ 23.4  ┆ 30.5   ┆ 28.9    ┆ 18.2  │
│ 1.0414  ┆ 25.3    ┆ 22  ┆ 154.0  ┆ … ┆ 24.0  ┆ 28.8   ┆ 25.2    ┆ 16.6  │
│ 1.0751  ┆ 10.4    ┆ 26  ┆ 184.75 ┆ … ┆ 22.8  ┆ 32.4   ┆ 29.4    ┆ 18.2  │
│ 1.034   ┆ 28.7    ┆ 24  ┆ 184.25 ┆ … ┆ 24.0  ┆ 32.2   ┆ 27.7    ┆ 17.7  │
│ …       ┆ …       ┆ …   ┆ …      ┆ … ┆ …     ┆ …      ┆ …       ┆ …     │
│ 1.0736  ┆ 11.0    ┆ 70  ┆ 134.25 ┆ … ┆ 21.5  ┆ 25.6   ┆ 25.7    ┆ 18.5  │
│ 1.0236  ┆ 33.6    ┆ 72  ┆ 201.0  ┆ … ┆ 23.2  ┆ 35.2   ┆ 28.6    ┆ 20.1  │
│ 1.0328  ┆ 29.3    ┆ 72  ┆ 186.75 ┆ … ┆ 21.5  ┆ 31.3   ┆ 27.2    ┆ 18.0  │
│ 1.0399  ┆ 26.0    ┆ 72  ┆ 190.75 ┆ … ┆ 22.7  ┆ 30.5   ┆ 29.4    ┆ 19.8  │
│ 1.0271  ┆ 31.9    ┆ 74  ┆ 207.5  ┆ … ┆ 24.6  ┆ 33.7   ┆ 30.0    ┆ 20.9  │
└─────────┴─────────┴─────┴────────┴───┴───────┴────────┴─────────┴───────┘

In [3]:
(X_train := 
    body
    .drop('bodyfat')
)

shape: (252, 14)
┌─────────┬─────┬────────┬────────┬───┬───────┬────────┬─────────┬───────┐
│ density ┆ age ┆ weight ┆ height ┆ … ┆ ankle ┆ biceps ┆ forearm ┆ wrist │
│ ---     ┆ --- ┆ ---    ┆ ---    ┆   ┆ ---   ┆ ---    ┆ ---     ┆ ---   │
│ f64     ┆ i64 ┆ f64    ┆ f64    ┆   ┆ f64   ┆ f64    ┆ f64     ┆ f64   │
╞═════════╪═════╪════════╪════════╪═══╪═══════╪════════╪═════════╪═══════╡
│ 1.0708  ┆ 23  ┆ 154.25 ┆ 67.75  ┆ … ┆ 21.9  ┆ 32.0   ┆ 27.4    ┆ 17.1  │
│ 1.0853  ┆ 22  ┆ 173.25 ┆ 72.25  ┆ … ┆ 23.4  ┆ 30.5   ┆ 28.9    ┆ 18.2  │
│ 1.0414  ┆ 22  ┆ 154.0  ┆ 66.25  ┆ … ┆ 24.0  ┆ 28.8   ┆ 25.2    ┆ 16.6  │
│ 1.0751  ┆ 26  ┆ 184.75 ┆ 72.25  ┆ … ┆ 22.8  ┆ 32.4   ┆ 29.4    ┆ 18.2  │
│ 1.034   ┆ 24  ┆ 184.25 ┆ 71.25  ┆ … ┆ 24.0  ┆ 32.2   ┆ 27.7    ┆ 17.7  │
│ …       ┆ …   ┆ …      ┆ …      ┆ … ┆ …     ┆ …      ┆ …       ┆ …     │
│ 1.0736  ┆ 70  ┆ 134.25 ┆ 67.0   ┆ … ┆ 21.5  ┆ 25.6   ┆ 25.7    ┆ 18.5  │
│ 1.0236  ┆ 72  ┆ 201.0  ┆ 69.75  ┆ … ┆ 23.2  ┆ 35.2   ┆ 28.6    ┆ 20.1  │
│ 1.0328  ┆ 72  ┆ 186.75 ┆ 66.0   ┆ … ┆ 21.5  ┆ 31.3   ┆ 27.2    ┆ 18.0  │
│ 1.0399  ┆ 72  ┆ 190.75 ┆ 70.5   ┆ … ┆ 22.7  ┆ 30.5   ┆ 29.4    ┆ 19.8  │
│ 1.0271  ┆ 74  ┆ 207.5  ┆ 70.0   ┆ … ┆ 24.6  ┆ 33.7   ┆ 30.0    ┆ 20.9  │
└─────────┴─────┴────────┴────────┴───┴───────┴────────┴─────────┴───────┘

In [4]:
(y_train := 
    body
    .select('bodyfat')

)

shape: (252, 1)
┌─────────┐
│ bodyfat │
│ ---     │
│ f64     │
╞═════════╡
│ 12.3    │
│ 6.1     │
│ 25.3    │
│ 10.4    │
│ 28.7    │
│ …       │
│ 11.0    │
│ 33.6    │
│ 29.3    │
│ 26.0    │
│ 31.9    │
└─────────┘

In [5]:
(  num_cols := X_train.columns
)

['density',
 'age',
 'weight',
 'height',
 'neck',
 'chest',
 'abdomen',
 'hip',
 'thigh',
 'knee',
 'ankle',
 'biceps',
 'forearm',
 'wrist']

### We'd probably use exclusively numeric pipe for this, since we're only dealing with numeric columns

In [6]:
(preprocess := 
 make_column_transformer(
     
    (StandardScaler(),num_cols)

 )

)

ColumnTransformer(transformers=[('standardscaler', StandardScaler(),
                                 ['density', 'age', 'weight', 'height', 'neck',
                                  'chest', 'abdomen', 'hip', 'thigh', 'knee',
                                  'ankle', 'biceps', 'forearm', 'wrist'])])

In [7]:
(folds := KFold(n_splits = 3, shuffle = True, random_state = 1490)

)

KFold(n_splits=3, random_state=1490, shuffle=True)

In [8]:

num_pipe = make_pipeline(SplineTransformer(), StandardScaler())

In [9]:
(model_pipe := make_pipeline(
    preprocess, 
    LinearRegression() # This is just a placeholder to start
)
)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('standardscaler',
                                                  StandardScaler(),
                                                  ['density', 'age', 'weight',
                                                   'height', 'neck', 'chest',
                                                   'abdomen', 'hip', 'thigh',
                                                   'knee', 'ankle', 'biceps',
                                                   'forearm', 'wrist'])])),
                ('linearregression', LinearRegression())])

In [13]:
param_grid = [

    { #Ridge 
        'regressor': [Ridge()],
        'regressor__alpha': [0.001, 0.01, 0.1, 1, 10, 100]
    },
    { #Lasso
        'regressor': [Lasso()],
        'regressor__alpha': [0.001, 0.01, 0.1, 1, 10, 100]

    },
    { #kNN
         'regressor': [KNeighborsRegressor()],
         'regressor__n_neighbors': [3, 5, 7, 11]
    },
    { #Linear 
         'regressor' : [LinearRegression()]

    }

]

#### Ridge Regression for both polynomial and spline transformations

In [15]:
(model_ridge_spline := 
make_pipeline(preprocess,
              SplineTransformer(),
              Ridge(alpha =1)
              )
)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('standardscaler',
                                                  StandardScaler(),
                                                  ['density', 'age', 'weight',
                                                   'height', 'neck', 'chest',
                                                   'abdomen', 'hip', 'thigh',
                                                   'knee', 'ankle', 'biceps',
                                                   'forearm', 'wrist'])])),
                ('splinetransformer', SplineTransformer()),
                ('ridge', Ridge(alpha=1))])

In [21]:
(model_ridge_poly := 
 make_pipeline(preprocess,
              PolynomialFeatures(),
              Ridge(alpha =1)
              )
 
 
 )

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('standardscaler',
                                                  StandardScaler(),
                                                  ['density', 'age', 'weight',
                                                   'height', 'neck', 'chest',
                                                   'abdomen', 'hip', 'thigh',
                                                   'knee', 'ankle', 'biceps',
                                                   'forearm', 'wrist'])])),
                ('polynomialfeatures', PolynomialFeatures()),
                ('ridge', Ridge(alpha=1))])

In [18]:
(grid_ridge :=
 
  {     
       'ridge__alpha': [0.001, 0.01, 0.1, 1, 10, 100],
        'ridge__max_iter': [5000]
}, {
       
        'functiontransformer__n_knots': [3, 4, 5],
        'ridge__alpha': [0.1, 1, 10]
    }

)

({'ridge__alpha': [0.001, 0.01, 0.1, 1, 10, 100], 'ridge__max_iter': [5000]},
 {'functiontransformer__n_knots': [3, 4, 5], 'ridge__alpha': [0.1, 1, 10]})

In [14]:
grid_spline = {
    'splinetransformer__n_knots': [3, 4, 5],
    'ridge__alpha': [0.001, 0.01, 0.1, 1, 10, 100],
    'ridge__max_iter': [5000]
}

In [16]:
grid_poly = {
    'polynomialfeatures__degree': [2, 3], # Added degree to make it a real search
    'ridge__alpha': [0.001, 0.01, 0.1, 1, 10, 100],
    'ridge__max_iter': [5000]
}

In [33]:
(gs_ridge_spline := GridSearchCV(model_ridge_spline,grid_spline, cv=folds,n_jobs=-1, verbose = 3, scoring ='neg_mean_squared_error')

 
)

GridSearchCV(cv=KFold(n_splits=3, random_state=1490, shuffle=True),
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('standardscaler',
                                                                         StandardScaler(),
                                                                         ['density',
                                                                          'age',
                                                                          'weight',
                                                                          'height',
                                                                          'neck',
                                                                          'chest',
                                                                          'abdomen',
                                                                          'hip',
                                                                          'thigh',
                                                                          'knee',
                                                                          'ankle',
                                                                          'biceps',
                                                                          'forearm',
                                                                          'wrist'])])),
                                       ('splinetransformer',
                                        SplineTransformer()),
                                       ('ridge', Ridge(alpha=1))]),
             n_jobs=-1,
             param_grid={'ridge__alpha': [0.001, 0.01, 0.1, 1, 10, 100],
                         'ridge__max_iter': [5000],
                         'splinetransformer__n_knots': [3, 4, 5]},
             scoring='neg_mean_squared_error', verbose=3)

In [34]:
gs_ridge_spline.fit(X_train, y_train)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

GridSearchCV(cv=KFold(n_splits=3, random_state=1490, shuffle=True),
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('standardscaler',
                                                                         StandardScaler(),
                                                                         ['density',
                                                                          'age',
                                                                          'weight',
                                                                          'height',
                                                                          'neck',
                                                                          'chest',
                                                                          'abdomen',
                                                                          'hip',
                                                                          'thigh',
                                                                          'knee',
                                                                          'ankle',
                                                                          'biceps',
                                                                          'forearm',
                                                                          'wrist'])])),
                                       ('splinetransformer',
                                        SplineTransformer()),
                                       ('ridge', Ridge(alpha=1))]),
             n_jobs=-1,
             param_grid={'ridge__alpha': [0.001, 0.01, 0.1, 1, 10, 100],
                         'ridge__max_iter': [5000],
                         'splinetransformer__n_knots': [3, 4, 5]},
             scoring='neg_mean_squared_error', verbose=3)

In [35]:
(gs_ridge_poly := GridSearchCV(model_ridge_poly,grid_poly, cv=folds,n_jobs=-1, verbose = 3, scoring ='neg_mean_squared_error')
 
)

GridSearchCV(cv=KFold(n_splits=3, random_state=1490, shuffle=True),
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('standardscaler',
                                                                         StandardScaler(),
                                                                         ['density',
                                                                          'age',
                                                                          'weight',
                                                                          'height',
                                                                          'neck',
                                                                          'chest',
                                                                          'abdomen',
                                                                          'hip',
                                                                          'thigh',
                                                                          'knee',
                                                                          'ankle',
                                                                          'biceps',
                                                                          'forearm',
                                                                          'wrist'])])),
                                       ('polynomialfeatures',
                                        PolynomialFeatures()),
                                       ('ridge', Ridge(alpha=1))]),
             n_jobs=-1,
             param_grid={'polynomialfeatures__degree': [2, 3],
                         'ridge__alpha': [0.001, 0.01, 0.1, 1, 10, 100],
                         'ridge__max_iter': [5000]},
             scoring='neg_mean_squared_error', verbose=3)

In [36]:
gs_ridge_poly.fit(X_train,y_train)

Fitting 3 folds for each of 12 candidates, totalling 36 fits

GridSearchCV(cv=KFold(n_splits=3, random_state=1490, shuffle=True),
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('standardscaler',
                                                                         StandardScaler(),
                                                                         ['density',
                                                                          'age',
                                                                          'weight',
                                                                          'height',
                                                                          'neck',
                                                                          'chest',
                                                                          'abdomen',
                                                                          'hip',
                                                                          'thigh',
                                                                          'knee',
                                                                          'ankle',
                                                                          'biceps',
                                                                          'forearm',
                                                                          'wrist'])])),
                                       ('polynomialfeatures',
                                        PolynomialFeatures()),
                                       ('ridge', Ridge(alpha=1))]),
             n_jobs=-1,
             param_grid={'polynomialfeatures__degree': [2, 3],
                         'ridge__alpha': [0.001, 0.01, 0.1, 1, 10, 100],
                         'ridge__max_iter': [5000]},
             scoring='neg_mean_squared_error', verbose=3)

### Lasso Regression for both spline & polynomial transformations

In [25]:
(model_lasso_spline := 
 make_pipeline(preprocess,
               SplineTransformer(),
               Lasso()
 )   
)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('standardscaler',
                                                  StandardScaler(),
                                                  ['density', 'age', 'weight',
                                                   'height', 'neck', 'chest',
                                                   'abdomen', 'hip', 'thigh',
                                                   'knee', 'ankle', 'biceps',
                                                   'forearm', 'wrist'])])),
                ('splinetransformer', SplineTransformer()),
                ('lasso', Lasso())])

In [37]:
(model_lasso_poly := 
 make_pipeline(preprocess,
               PolynomialFeatures(),
               Lasso()
               )


)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('standardscaler',
                                                  StandardScaler(),
                                                  ['density', 'age', 'weight',
                                                   'height', 'neck', 'chest',
                                                   'abdomen', 'hip', 'thigh',
                                                   'knee', 'ankle', 'biceps',
                                                   'forearm', 'wrist'])])),
                ('polynomialfeatures', PolynomialFeatures()),
                ('lasso', Lasso())])

In [39]:
(grid_lasso := 
 
{
     'lasso__alpha': [0.001, 0.01, 0.1, 1, 10, 100],
    'lasso__max_iter': [10000]


}

)

{'lasso__alpha': [0.001, 0.01, 0.1, 1, 10, 100], 'lasso__max_iter': [10000]}

In [38]:
grid_lasso_spline = {
    'splinetransformer__n_knots': [3, 4, 5],
    'lasso__alpha': [0.001, 0.01, 0.1, 1, 10, 100],
    'lasso__max_iter': [10000]
}

In [40]:
grid_lasso_poly = {
    'polynomialfeatures__degree': [2, 3],
    'lasso__alpha': [0.001, 0.01, 0.1, 1, 10, 100],
    'lasso__max_iter': [10000]
}

In [64]:
(gs_lasso_spline := GridSearchCV(model_lasso_spline,grid_lasso_spline, cv = folds, n_jobs =-1, verbose = 3, scoring = 'neg_mean_squared_error'))

GridSearchCV(cv=KFold(n_splits=3, random_state=1490, shuffle=True),
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('standardscaler',
                                                                         StandardScaler(),
                                                                         ['density',
                                                                          'age',
                                                                          'weight',
                                                                          'height',
                                                                          'neck',
                                                                          'chest',
                                                                          'abdomen',
                                                                          'hip',
                                                                          'thigh',
                                                                          'knee',
                                                                          'ankle',
                                                                          'biceps',
                                                                          'forearm',
                                                                          'wrist'])])),
                                       ('splinetransformer',
                                        SplineTransformer()),
                                       ('lasso', Lasso())]),
             n_jobs=-1,
             param_grid={'lasso__alpha': [0.001, 0.01, 0.1, 1, 10, 100],
                         'lasso__max_iter': [10000],
                         'splinetransformer__n_knots': [3, 4, 5]},
             scoring='neg_mean_squared_error', verbose=3)

In [44]:
(gs_lasso_poly := GridSearchCV(model_lasso_poly,grid_lasso_poly, cv = folds, n_jobs =-1, verbose = 3, scoring = 'neg_mean_squared_error'))

GridSearchCV(cv=KFold(n_splits=3, random_state=1490, shuffle=True),
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('standardscaler',
                                                                         StandardScaler(),
                                                                         ['density',
                                                                          'age',
                                                                          'weight',
                                                                          'height',
                                                                          'neck',
                                                                          'chest',
                                                                          'abdomen',
                                                                          'hip',
                                                                          'thigh',
                                                                          'knee',
                                                                          'ankle',
                                                                          'biceps',
                                                                          'forearm',
                                                                          'wrist'])])),
                                       ('polynomialfeatures',
                                        PolynomialFeatures()),
                                       ('lasso', Lasso())]),
             n_jobs=-1,
             param_grid={'lasso__alpha': [0.001, 0.01, 0.1, 1, 10, 100],
                         'lasso__max_iter': [10000],
                         'polynomialfeatures__degree': [2, 3]},
             scoring='neg_mean_squared_error', verbose=3)

In [65]:
(gs_lasso_spline.fit(X_train, y_train))

Fitting 3 folds for each of 18 candidates, totalling 54 fits

GridSearchCV(cv=KFold(n_splits=3, random_state=1490, shuffle=True),
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('standardscaler',
                                                                         StandardScaler(),
                                                                         ['density',
                                                                          'age',
                                                                          'weight',
                                                                          'height',
                                                                          'neck',
                                                                          'chest',
                                                                          'abdomen',
                                                                          'hip',
                                                                          'thigh',
                                                                          'knee',
                                                                          'ankle',
                                                                          'biceps',
                                                                          'forearm',
                                                                          'wrist'])])),
                                       ('splinetransformer',
                                        SplineTransformer()),
                                       ('lasso', Lasso())]),
             n_jobs=-1,
             param_grid={'lasso__alpha': [0.001, 0.01, 0.1, 1, 10, 100],
                         'lasso__max_iter': [10000],
                         'splinetransformer__n_knots': [3, 4, 5]},
             scoring='neg_mean_squared_error', verbose=3)

In [66]:
(gs_lasso_poly.fit(X_train, y_train))

Fitting 3 folds for each of 12 candidates, totalling 36 fits

GridSearchCV(cv=KFold(n_splits=3, random_state=1490, shuffle=True),
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('standardscaler',
                                                                         StandardScaler(),
                                                                         ['density',
                                                                          'age',
                                                                          'weight',
                                                                          'height',
                                                                          'neck',
                                                                          'chest',
                                                                          'abdomen',
                                                                          'hip',
                                                                          'thigh',
                                                                          'knee',
                                                                          'ankle',
                                                                          'biceps',
                                                                          'forearm',
                                                                          'wrist'])])),
                                       ('polynomialfeatures',
                                        PolynomialFeatures()),
                                       ('lasso', Lasso())]),
             n_jobs=-1,
             param_grid={'lasso__alpha': [0.001, 0.01, 0.1, 1, 10, 100],
                         'lasso__max_iter': [10000],
                         'polynomialfeatures__degree': [2, 3]},
             scoring='neg_mean_squared_error', verbose=3)

### kNN for both spline & poly transformation

In [46]:
(model_knn_spline := 
 make_pipeline(preprocess,
               SplineTransformer(),
               KNeighborsRegressor()
 )
)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('standardscaler',
                                                  StandardScaler(),
                                                  ['density', 'age', 'weight',
                                                   'height', 'neck', 'chest',
                                                   'abdomen', 'hip', 'thigh',
                                                   'knee', 'ankle', 'biceps',
                                                   'forearm', 'wrist'])])),
                ('splinetransformer', SplineTransformer()),
                ('kneighborsregressor', KNeighborsRegressor())])

In [47]:
(model_knn_poly :=
 make_pipeline(preprocess, 
               PolynomialFeatures(),
               KNeighborsRegressor()
 )
)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('standardscaler',
                                                  StandardScaler(),
                                                  ['density', 'age', 'weight',
                                                   'height', 'neck', 'chest',
                                                   'abdomen', 'hip', 'thigh',
                                                   'knee', 'ankle', 'biceps',
                                                   'forearm', 'wrist'])])),
                ('polynomialfeatures', PolynomialFeatures()),
                ('kneighborsregressor', KNeighborsRegressor())])

In [48]:
(grid_knn := 
 {
   'kneighborsregressor__n_neighbors': [3, 5, 7, 11, 15, 21],
   'kneighborsregressor__weights': ['uniform', 'distance'],
   'kneighborsregressor__p': [1, 2]

 }


)

{'kneighborsregressor__n_neighbors': [3, 5, 7, 11, 15, 21],
 'kneighborsregressor__weights': ['uniform', 'distance'],
 'kneighborsregressor__p': [1, 2]}

In [57]:
(grid_knn_spline :=
    {'splinetransformer__n_knots': [3, 4, 5], 
    'kneighborsregressor__n_neighbors' : [3, 5, 7, 11, 15],
    'kneighborsregressor__weights': ['uniform', 'distance']
    }
)

{'splinetransformer__n_knots': [3, 4, 5],
 'kneighborsregressor__n_neighbors': [3, 5, 7, 11, 15],
 'kneighborsregressor__weights': ['uniform', 'distance']}

In [58]:
(grid_knn_poly :=
 {
  'polynomialfeatures__degree': [2, 3], 
  'kneighborsregressor__n_neighbors': [3, 5, 7, 11, 15],
  'kneighborsregressor__weights': ['uniform', 'distance']
 }
)

{'polynomialfeatures__degree': [2, 3],
 'kneighborsregressor__n_neighbors': [3, 5, 7, 11, 15],
 'kneighborsregressor__weights': ['uniform', 'distance']}

In [60]:
(gs_knn_spline := GridSearchCV(model_knn_spline,grid_knn_spline, cv = folds,n_jobs=-1, verbose = 3, scoring = "neg_mean_squared_error"

)
)

GridSearchCV(cv=KFold(n_splits=3, random_state=1490, shuffle=True),
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('standardscaler',
                                                                         StandardScaler(),
                                                                         ['density',
                                                                          'age',
                                                                          'weight',
                                                                          'height',
                                                                          'neck',
                                                                          'chest',
                                                                          'abdomen',
                                                                          'hip',
                                                                          'thigh',
                                                                          'knee',
                                                                          'ankle',
                                                                          'biceps',
                                                                          'forearm',
                                                                          'wrist'])])),
                                       ('splinetransformer',
                                        SplineTransformer()),
                                       ('kneighborsregressor',
                                        KNeighborsRegressor())]),
             n_jobs=-1,
             param_grid={'kneighborsregressor__n_neighbors': [3, 5, 7, 11, 15],
                         'kneighborsregressor__weights': ['uniform',
                                                          'distance'],
                         'splinetransformer__n_knots': [3, 4, 5]},
             scoring='neg_mean_squared_error', verbose=3)

In [61]:
gs_knn_spline.fit(X_train,y_train)

Fitting 3 folds for each of 30 candidates, totalling 90 fits

GridSearchCV(cv=KFold(n_splits=3, random_state=1490, shuffle=True),
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('standardscaler',
                                                                         StandardScaler(),
                                                                         ['density',
                                                                          'age',
                                                                          'weight',
                                                                          'height',
                                                                          'neck',
                                                                          'chest',
                                                                          'abdomen',
                                                                          'hip',
                                                                          'thigh',
                                                                          'knee',
                                                                          'ankle',
                                                                          'biceps',
                                                                          'forearm',
                                                                          'wrist'])])),
                                       ('splinetransformer',
                                        SplineTransformer()),
                                       ('kneighborsregressor',
                                        KNeighborsRegressor())]),
             n_jobs=-1,
             param_grid={'kneighborsregressor__n_neighbors': [3, 5, 7, 11, 15],
                         'kneighborsregressor__weights': ['uniform',
                                                          'distance'],
                         'splinetransformer__n_knots': [3, 4, 5]},
             scoring='neg_mean_squared_error', verbose=3)

In [62]:
(gs_knn_poly := GridSearchCV(model_knn_poly, grid_knn_poly, cv = folds, n_jobs =-1, verbose = 3, scoring = 'neg_mean_squared_error') )

GridSearchCV(cv=KFold(n_splits=3, random_state=1490, shuffle=True),
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('standardscaler',
                                                                         StandardScaler(),
                                                                         ['density',
                                                                          'age',
                                                                          'weight',
                                                                          'height',
                                                                          'neck',
                                                                          'chest',
                                                                          'abdomen',
                                                                          'hip',
                                                                          'thigh',
                                                                          'knee',
                                                                          'ankle',
                                                                          'biceps',
                                                                          'forearm',
                                                                          'wrist'])])),
                                       ('polynomialfeatures',
                                        PolynomialFeatures()),
                                       ('kneighborsregressor',
                                        KNeighborsRegressor())]),
             n_jobs=-1,
             param_grid={'kneighborsregressor__n_neighbors': [3, 5, 7, 11, 15],
                         'kneighborsregressor__weights': ['uniform',
                                                          'distance'],
                         'polynomialfeatures__degree': [2, 3]},
             scoring='neg_mean_squared_error', verbose=3)

In [63]:
(gs_knn_poly.fit(X_train, y_train))

Fitting 3 folds for each of 20 candidates, totalling 60 fits

GridSearchCV(cv=KFold(n_splits=3, random_state=1490, shuffle=True),
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('standardscaler',
                                                                         StandardScaler(),
                                                                         ['density',
                                                                          'age',
                                                                          'weight',
                                                                          'height',
                                                                          'neck',
                                                                          'chest',
                                                                          'abdomen',
                                                                          'hip',
                                                                          'thigh',
                                                                          'knee',
                                                                          'ankle',
                                                                          'biceps',
                                                                          'forearm',
                                                                          'wrist'])])),
                                       ('polynomialfeatures',
                                        PolynomialFeatures()),
                                       ('kneighborsregressor',
                                        KNeighborsRegressor())]),
             n_jobs=-1,
             param_grid={'kneighborsregressor__n_neighbors': [3, 5, 7, 11, 15],
                         'kneighborsregressor__weights': ['uniform',
                                                          'distance'],
                         'polynomialfeatures__degree': [2, 3]},
             scoring='neg_mean_squared_error', verbose=3)

### Linear for both splines & polynomial regression

In [67]:
(grid_ols_spline :=

    {
        # spline
        'splinetransformer__n_knots': [3, 4, 5],
        'splinetransformer__degree': [2, 3]
    }

)

{'splinetransformer__n_knots': [3, 4, 5], 'splinetransformer__degree': [2, 3]}

In [ ]:
(model_ols_spline := 
 make_pipeline(preprocess, 
               SplineTransformer(),
               LinearRegression()
    
 )
)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('standardscaler',
                                                  StandardScaler(),
                                                  ['density', 'age', 'weight',
                                                   'height', 'neck', 'chest',
                                                   'abdomen', 'hip', 'thigh',
                                                   'knee', 'ankle', 'biceps',
                                                   'forearm', 'wrist'])])),
                ('splinetransformer', SplineTransformer()),
                ('linearregression', LinearRegression())])

In [69]:
(gs_ols_spline := GridSearchCV(model_ols_spline,grid_ols_spline,cv=folds,n_jobs=-1, verbose=3,scoring='neg_mean_squared_error' )

)

GridSearchCV(cv=KFold(n_splits=3, random_state=1490, shuffle=True),
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('standardscaler',
                                                                         StandardScaler(),
                                                                         ['density',
                                                                          'age',
                                                                          'weight',
                                                                          'height',
                                                                          'neck',
                                                                          'chest',
                                                                          'abdomen',
                                                                          'hip',
                                                                          'thigh',
                                                                          'knee',
                                                                          'ankle',
                                                                          'biceps',
                                                                          'forearm',
                                                                          'wrist'])])),
                                       ('splinetransformer',
                                        SplineTransformer()),
                                       ('linearregression',
                                        LinearRegression())]),
             n_jobs=-1,
             param_grid={'splinetransformer__degree': [2, 3],
                         'splinetransformer__n_knots': [3, 4, 5]},
             scoring='neg_mean_squared_error', verbose=3)

In [70]:
(gs_ols_spline.fit(X_train, y_train)
)

Fitting 3 folds for each of 6 candidates, totalling 18 fits

GridSearchCV(cv=KFold(n_splits=3, random_state=1490, shuffle=True),
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('standardscaler',
                                                                         StandardScaler(),
                                                                         ['density',
                                                                          'age',
                                                                          'weight',
                                                                          'height',
                                                                          'neck',
                                                                          'chest',
                                                                          'abdomen',
                                                                          'hip',
                                                                          'thigh',
                                                                          'knee',
                                                                          'ankle',
                                                                          'biceps',
                                                                          'forearm',
                                                                          'wrist'])])),
                                       ('splinetransformer',
                                        SplineTransformer()),
                                       ('linearregression',
                                        LinearRegression())]),
             n_jobs=-1,
             param_grid={'splinetransformer__degree': [2, 3],
                         'splinetransformer__n_knots': [3, 4, 5]},
             scoring='neg_mean_squared_error', verbose=3)

In [71]:
grid_ols_poly = {
    'polynomialfeatures__degree': [2, 3]
}

In [72]:
(model_ols_poly := 
 make_pipeline(preprocess, 
               PolynomialFeatures(),
               LinearRegression(),
 )
 )

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('standardscaler',
                                                  StandardScaler(),
                                                  ['density', 'age', 'weight',
                                                   'height', 'neck', 'chest',
                                                   'abdomen', 'hip', 'thigh',
                                                   'knee', 'ankle', 'biceps',
                                                   'forearm', 'wrist'])])),
                ('polynomialfeatures', PolynomialFeatures()),
                ('linearregression', LinearRegression())])

In [73]:
(gs_ols_poly := GridSearchCV(model_ols_poly,grid_ols_poly,cv=folds,n_jobs=-1, verbose=3,scoring='neg_mean_squared_error' )
 
 
 )

GridSearchCV(cv=KFold(n_splits=3, random_state=1490, shuffle=True),
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('standardscaler',
                                                                         StandardScaler(),
                                                                         ['density',
                                                                          'age',
                                                                          'weight',
                                                                          'height',
                                                                          'neck',
                                                                          'chest',
                                                                          'abdomen',
                                                                          'hip',
                                                                          'thigh',
                                                                          'knee',
                                                                          'ankle',
                                                                          'biceps',
                                                                          'forearm',
                                                                          'wrist'])])),
                                       ('polynomialfeatures',
                                        PolynomialFeatures()),
                                       ('linearregression',
                                        LinearRegression())]),
             n_jobs=-1, param_grid={'polynomialfeatures__degree': [2, 3]},
             scoring='neg_mean_squared_error', verbose=3)

In [74]:
(gs_ols_poly.fit(X_train, y_train))

Fitting 3 folds for each of 2 candidates, totalling 6 fits

GridSearchCV(cv=KFold(n_splits=3, random_state=1490, shuffle=True),
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('standardscaler',
                                                                         StandardScaler(),
                                                                         ['density',
                                                                          'age',
                                                                          'weight',
                                                                          'height',
                                                                          'neck',
                                                                          'chest',
                                                                          'abdomen',
                                                                          'hip',
                                                                          'thigh',
                                                                          'knee',
                                                                          'ankle',
                                                                          'biceps',
                                                                          'forearm',
                                                                          'wrist'])])),
                                       ('polynomialfeatures',
                                        PolynomialFeatures()),
                                       ('linearregression',
                                        LinearRegression())]),
             n_jobs=-1, param_grid={'polynomialfeatures__degree': [2, 3]},
             scoring='neg_mean_squared_error', verbose=3)

### Comparison of all methods for transformers and regressors 
##### Looking at all possible combinations between the outcomes of polynomial or spline transformers and lasso, ridge, linear and kNN regression models.

### Comparison of Parameters

In [77]:
( params := {
   "ridge and spline" : {"params" : gs_ridge_spline.best_params_},
   "ridge and poly"   : {"params": gs_ridge_poly.best_params_},
   "lasso and spline" : {"params" : gs_lasso_spline.best_params_},
   "lasso and poly"   : {"params" : gs_lasso_poly.best_params_},
   "kNN and spline"  : {"params" : gs_knn_spline.best_params_},
   "kNN and poly" :     {"params" : gs_knn_poly.best_params_},
   "linear and spline" : {"params" : gs_ols_spline.best_params_},
   "linear and poly" : {"params" : gs_ols_poly.best_params_}
 }
)

{'ridge and spline': {'params': {'ridge__alpha': 0.001,
   'ridge__max_iter': 5000,
   'splinetransformer__n_knots': 3}},
 'ridge and poly': {'params': {'polynomialfeatures__degree': 2,
   'ridge__alpha': 0.1,
   'ridge__max_iter': 5000}},
 'lasso and spline': {'params': {'lasso__alpha': 0.001,
   'lasso__max_iter': 10000,
   'splinetransformer__n_knots': 3}},
 'lasso and poly': {'params': {'lasso__alpha': 0.1,
   'lasso__max_iter': 10000,
   'polynomialfeatures__degree': 2}},
 'kNN and spline': {'params': {'kneighborsregressor__n_neighbors': 3,
   'kneighborsregressor__weights': 'distance',
   'splinetransformer__n_knots': 4}},
 'kNN and poly': {'params': {'kneighborsregressor__n_neighbors': 3,
   'kneighborsregressor__weights': 'distance',
   'polynomialfeatures__degree': 3}},
 'linear and spline': {'params': {'splinetransformer__degree': 2,
   'splinetransformer__n_knots': 3}},
 'linear and poly': {'params': {'polynomialfeatures__degree': 2}}}

In [78]:
(best_score :=  {
        "Ridge and spline" : {"MSE": -gs_ridge_spline.best_score_},
        "Ridge and poly" : {"MSE": -gs_ridge_poly.best_score_},
        "Lasso and spline" : {"MSE":  -gs_lasso_spline.best_score_},
        "Lasso and poly" : {"MSE" : -gs_lasso_poly.best_score_},
        "kNN and spline" : {"MSE" :  -gs_knn_spline.best_score_},
        "kNN and poly" : {"MSE" :  -gs_knn_poly.best_score_},
        "ols and spline" : {"MSE" : -gs_ols_spline.best_score_},
        "ols and poly" : {"MSE" :  -gs_ols_poly.best_score_}



}
 
 
 )

{'Ridge and spline': {'MSE': np.float64(0.2763235751963632)},
 'Ridge and poly': {'MSE': np.float64(0.21594584890695626)},
 'Lasso and spline': {'MSE': np.float64(0.3138443258185521)},
 'Lasso and poly': {'MSE': np.float64(0.10257324508262948)},
 'kNN and spline': {'MSE': np.float64(10.560991740783477)},
 'kNN and poly': {'MSE': np.float64(15.28341560305122)},
 'ols and spline': {'MSE': np.float64(0.2818790040402815)},
 'ols and poly': {'MSE': np.float64(0.39164244517436614)}}

### According to a list of all our transformer and regressor combinations we have, the lasso and polynomial transformer and regressor combination is the one with the *lowest* Mean Sqaure Error or the average of the sqaured deviation between our predicted values and our outcome values